<a href="https://colab.research.google.com/github/MuhamedRagabbb/DEEP_LEARNING_PROJECTS/blob/main/tutorial1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

In [ ]:
if torch.cuda.is_available():
  device=torch.device("cuda")
else:
  device=torch.device("cpu")

print(device)

cpu


#list

In [ ]:
my_list=[1,2,3,4]
my_list

[1, 2, 3, 4]

#numpy array

In [ ]:
nparray=np.random.rand(3,4)
nparray

array([[0.94104916, 0.02431085, 0.9096055 , 0.48300981],
       [0.45640274, 0.24575771, 0.85227855, 0.87006589],
       [0.25372266, 0.4168181 , 0.76785755, 0.49489938]])

In [ ]:
nparray.dtype

dtype('float64')

#tensors

In [ ]:
tensorarray= torch.randn(3,4)
tensorarray

tensor([[-0.2678, -0.1944, -1.4223, -0.8754],
        [ 1.9233, -1.0891,  1.3201,  0.4705],
        [-1.6333,  0.0845,  0.4683,  0.5168]])

In [ ]:
tensorarray.dtype

torch.float32

In [ ]:
tensor_3d=torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

#create a tensor from numpy array

In [ ]:
num_tensor=torch.tensor(nparray)
num_tensor

tensor([[0.9410, 0.0243, 0.9096, 0.4830],
        [0.4564, 0.2458, 0.8523, 0.8701],
        [0.2537, 0.4168, 0.7679, 0.4949]], dtype=torch.float64)

#tensor operations

In [ ]:
my_torch= torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# reshape && view


## first reshape

In [ ]:
my_torch=my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
# if we don't know the num of columns
my_torch2=torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch2=my_torch2.reshape(2,-1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

## second view

In [ ]:
my_torch3=torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch3=my_torch3.view(2,5)
my_torch3

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

##if we make update to the tensor the reshape and view will reflected

In [ ]:
myTorch4=torch.arange(16)
myTorch4

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
mytorch5=myTorch4.reshape(4,4)
mytorch5

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [ ]:
myTorch4[1]=4444
myTorch4

tensor([   0, 4444,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
          12,   13,   14,   15])

In [ ]:
mytorch5

tensor([[   0, 4444,    2,    3],
        [   4,    5,    6,    7],
        [   8,    9,   10,   11],
        [  12,   13,   14,   15]])

#slices

In [ ]:
myTorch6=torch.arange(10)
myTorch6

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
myTorch6[6]

tensor(6)

In [ ]:
myTorch7=myTorch6.reshape(5,2)
myTorch7

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [ ]:
#grab a slice
myTorch7[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])