<a href="https://colab.research.google.com/github/MuhamedRagabbb/DEEP_LEARNING_PROJECTS/blob/main/tutorial2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch , numpy as np

#Tensor Math Operations

In [2]:
tensor_1=torch.tensor([1,2,3,4])
tensor_2=torch.tensor([5,6,7,8])

##addition

### we have two wayes first one :

In [3]:
tensor_1+tensor_2

tensor([ 6,  8, 10, 12])

### second one

In [4]:
torch.add(tensor_1,tensor_2)

tensor([ 6,  8, 10, 12])

## subtraction

### first method

In [5]:
tensor_1-tensor_2

tensor([-4, -4, -4, -4])

### second method

In [6]:
torch.sub(tensor_1,tensor_2)

tensor([-4, -4, -4, -4])

## multiplication

### first method

In [7]:
tensor_1 * tensor_2

tensor([ 5, 12, 21, 32])

### second method

In [8]:
torch.mul(tensor_1,tensor_2)

tensor([ 5, 12, 21, 32])

## devision

### first method

In [9]:
tensor_1 / tensor_2

tensor([0.2000, 0.3333, 0.4286, 0.5000])

### second method

In [10]:
torch.div(tensor_1,tensor_2)

tensor([0.2000, 0.3333, 0.4286, 0.5000])

## remainder

### first method

In [11]:
tensor_1 % tensor_2

tensor([1, 2, 3, 4])

### second method

In [12]:
torch.remainder(tensor_1,tensor_2)

tensor([1, 2, 3, 4])

## power

In [13]:
torch.pow(tensor_1,tensor_2)

tensor([    1,    64,  2187, 65536])